/*I am trying to produce the following type of message or error whatever you say
Dm: Incorrect combination of Math.max and Math.min (DM_INVALID_MIN_MAX)
This code tries to limit the value bounds using the construct like Math.min(0, Math.max(100, value)). However the order of the constants is incorrect: it should be Math.min(100, Math.max(0, value)). As the result this code always produces the same result (or NaN if the value is NaN).
If it is not generated by the previous program*/
import java.io.*;
class MainsClass
{
	public static void main(String args[])throws IOException, Exception
	{
		int value1,value2;
		BufferedReader z=new BufferedReader(new InputStreamReader(System.in));
		value1=Integer.parseInt(z.readLine());
		value2=Math.min(100, Math.max(0, value1));
		System.out.println("The value is:"+value2);
	}
}
