/*I am trying to generate the following type of error
SF: Switch statement found where default case is missing (SF_SWITCH_NO_DEFAULT)
This method contains a switch statement where default case is missing. Usually you need to provide a default case.
Because the analysis only looks at the generated bytecode, this warning can be incorrect triggered if the default case is at the end of the switch statement and the switch statement doesn't contain break statements for other cases. */
import java.io.*;
class MainsClass
{
	public static void main(String args[]) throws IOException
	{
		grading('A');
	        grading('C');
		grading('E');
	        grading('G');
		
	}
	public static void grading(char grade) 
	{
		int success;
		switch(grade)
		{
			case 'A':System.out.println("Excellent grade");
	            		 success = 1;
			case 'B':System.out.println("Excellent grade");
	            		 success = 1;
			case 'C':System.out.println("Good grade");
				 success = 1;
				 break;
			case 'D':
			case 'E':
			case 'F':System.out.println("Low grade");
				 success = 0;
				 break;
	  	}
		passTheCourse(success);
	}
	public static void passTheCourse(int success)
	{
	        switch (success) 
	        {
		        case -1:System.out.println("No result");
	            		break;
	        	case 0:System.out.println("Final result: Fail");
	            		break;
		        case 1:System.out.println("Final result: Success");
		               break;
	        	default:System.out.println("Unknown result");
	            		break;
		}
	}
}
